env:
  browser: true
extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
globals:
  $: false
  chrome: false
overrides:
  - files:
      - '**/*.ts'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: './tsconfig.json'
    rules:
      no-unused-vars: off
      valid-jsdoc: off

rules:
  no-console: off
  require-jsdoc: off
  import/no-unresolved: off
