env:
  browser: true
  node: true
extends:
- "@ianwremmel"
- "@ianwremmel/eslint-config/import"
globals:
  $: false
  chrome: false
rules:
  no-console: off
  import/no-commonjs: off
  import/unambiguous: off
