restore_cache: &restore_cache
  keys:
    - node-modules-{{ arch }}-{{ checksum "package-lock.json" }}

save_cache: &save_cache
  key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
  paths:
    - node_modules
  when: always

docker: &docker
  - image: 'node:10'

commands:
  pre_commands:
    steps:
      - checkout
      - attach_workspace:
          at: '.'

version: 2.1
jobs:
  build:
    docker: *docker
    steps:
      - pre_commands
      - run: npm run build
      - run: npm run archive
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
            - ./artifacts
      - store_artifacts:
          path: ./artifacts

  install:
    docker: *docker
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: npm ci
      - save_cache: *save_cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    docker: *docker
    steps:
      - pre_commands
      - run: npm run lint

  validate:
    docker: *docker
    steps:
      - pre_commands
      - run: npm run validate

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - validate:
          requires:
            - build
